version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build ja"
          command: |
            cp Dockerfile.production Dockerfile
            docker build -t tamesuseiko/ci:latest
            docker built -t tamesuseiko/ci:${CIRCLE_SHA1}
            docker push tamesuseiko/ci:latest
            docker push tamesuseiko/ci:${CIRCLE_SHA1}
      - run: echo Done
